# Generated by Django 4.0.4 on 2022-05-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_user_salt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date']},
        ),
    ]
